server:
  port: 8084

spring:
  application:
    name: career-service
  config:
    import: optional:configserver:http://config-service:8888
  cloud:
    config:
      uri: http://config-service:8888
      fail-fast: false
      retry:
        max-attempts: 6
        initial-interval: 1000
        max-interval: 2000

  datasource:
    datasource:
      url: jdbc:postgresql://postgres:5432/careerdb
      username: postgres
      password: 123456
      driver-class-name: org.postgresql.Driver
    jpa:
      hibernate:
        ddl-auto: create
      show-sql: true

eureka:
  client:
    service-url:
      defaultZone: http://discovery-service:8761/eureka/
    fetch-registry: true
    register-with-eureka: true
    registryFetchIntervalSeconds: 5
  instance:
    prefer-ip-address: true
    instance-id: ${spring.application.name}:${random.uuid}
